// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userLogin.proto

package grpc.examples.userLogin;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.LoginStatus status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.LoginStatus status = 1;</code>
   */
  grpc.examples.userLogin.LoginStatus getStatus();

  /**
   * <code>string userStatus = 2;</code>
   */
  java.lang.String getUserStatus();
  /**
   * <code>string userStatus = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserStatusBytes();
}
