// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userLogin.proto

package grpc.examples.userLogin;

/**
 * Protobuf enum {@code LoginStatus}
 */
public enum LoginStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LOGIN_SUCCESSFULL = 0;</code>
   */
  LOGIN_SUCCESSFULL(0),
  /**
   * <code>INCORRECT_LOGIN_DETAILS = 1;</code>
   */
  INCORRECT_LOGIN_DETAILS(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>LOGIN_SUCCESSFULL = 0;</code>
   */
  public static final int LOGIN_SUCCESSFULL_VALUE = 0;
  /**
   * <code>INCORRECT_LOGIN_DETAILS = 1;</code>
   */
  public static final int INCORRECT_LOGIN_DETAILS_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LoginStatus valueOf(int value) {
    return forNumber(value);
  }

  public static LoginStatus forNumber(int value) {
    switch (value) {
      case 0: return LOGIN_SUCCESSFULL;
      case 1: return INCORRECT_LOGIN_DETAILS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LoginStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LoginStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LoginStatus>() {
          public LoginStatus findValueByNumber(int number) {
            return LoginStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return grpc.examples.userLogin.userLoginProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final LoginStatus[] VALUES = values();

  public static LoginStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private LoginStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:LoginStatus)
}

