// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S3-healthActivities.proto

package grpc.service3;

public interface ExerciseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:health_activities.ExerciseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string exercise_type = 1;</code>
   */
  java.lang.String getExerciseType();
  /**
   * <code>string exercise_type = 1;</code>
   */
  com.google.protobuf.ByteString
      getExerciseTypeBytes();
}
