// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S3-healthActivities.proto

package grpc.service3;

public final class HealthActivitiesProto {
  private HealthActivitiesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_health_activities_ExerciseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_health_activities_ExerciseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_health_activities_ExerciseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_health_activities_ExerciseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_health_activities_NutritionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_health_activities_NutritionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_health_activities_NutritionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_health_activities_NutritionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_health_activities_EmergencyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_health_activities_EmergencyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_health_activities_EmergencyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_health_activities_EmergencyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_health_activities_MedicationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_health_activities_MedicationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_health_activities_MedicationReminder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_health_activities_MedicationReminder_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031S3-healthActivities.proto\022\021health_acti" +
      "vities\"(\n\017ExerciseRequest\022\025\n\rexercise_ty" +
      "pe\030\001 \001(\t\"u\n\020ExerciseResponse\022\030\n\020duration" +
      "_minutes\030\001 \001(\005\022\027\n\017calories_burned\030\002 \001(\002\022" +
      "\026\n\016avg_heart_rate\030\003 \001(\005\022\026\n\016max_heart_rat" +
      "e\030\004 \001(\005\"9\n\020NutritionRequest\022\014\n\004meal\030\001 \001(" +
      "\t\022\027\n\017calories_intake\030\002 \001(\005\"N\n\021NutritionR" +
      "esponse\022\035\n\025total_calories_intake\030\001 \001(\005\022\032" +
      "\n\022is_caloric_surplus\030\002 \001(\010\"$\n\020EmergencyR" +
      "equest\022\020\n\010username\030\001 \001(\t\"+\n\021EmergencyRes" +
      "ponse\022\026\n\016call_ambulance\030\001 \001(\010\"%\n\021Medicat" +
      "ionRequest\022\020\n\010username\030\001 \001(\t\"6\n\022Medicati" +
      "onReminder\022\014\n\004time\030\001 \001(\t\022\022\n\nmedication\030\002" +
      " \001(\t2\232\003\n\027HealthActivitiesService\022U\n\010Exer" +
      "cise\022\".health_activities.ExerciseRequest" +
      "\032#.health_activities.ExerciseResponse\"\000\022" +
      "e\n\024NutritionInformation\022#.health_activit" +
      "ies.NutritionRequest\032$.health_activities" +
      ".NutritionResponse\"\000(\001\022\\\n\rCallAmbulance\022" +
      "#.health_activities.EmergencyRequest\032$.h" +
      "ealth_activities.EmergencyResponse\"\000\022c\n\020" +
      "RemindMedication\022$.health_activities.Med" +
      "icationRequest\032%.health_activities.Medic" +
      "ationReminder\"\0000\001B(\n\rgrpc.service3B\025Heal" +
      "thActivitiesProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_health_activities_ExerciseRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_health_activities_ExerciseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_health_activities_ExerciseRequest_descriptor,
        new java.lang.String[] { "ExerciseType", });
    internal_static_health_activities_ExerciseResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_health_activities_ExerciseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_health_activities_ExerciseResponse_descriptor,
        new java.lang.String[] { "DurationMinutes", "CaloriesBurned", "AvgHeartRate", "MaxHeartRate", });
    internal_static_health_activities_NutritionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_health_activities_NutritionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_health_activities_NutritionRequest_descriptor,
        new java.lang.String[] { "Meal", "CaloriesIntake", });
    internal_static_health_activities_NutritionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_health_activities_NutritionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_health_activities_NutritionResponse_descriptor,
        new java.lang.String[] { "TotalCaloriesIntake", "IsCaloricSurplus", });
    internal_static_health_activities_EmergencyRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_health_activities_EmergencyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_health_activities_EmergencyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_health_activities_EmergencyResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_health_activities_EmergencyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_health_activities_EmergencyResponse_descriptor,
        new java.lang.String[] { "CallAmbulance", });
    internal_static_health_activities_MedicationRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_health_activities_MedicationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_health_activities_MedicationRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_health_activities_MedicationReminder_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_health_activities_MedicationReminder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_health_activities_MedicationReminder_descriptor,
        new java.lang.String[] { "Time", "Medication", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
