// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S3-healthActivities.proto

package grpc.service3;

public interface MedicationReminderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:health_activities.MedicationReminder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The time of the medication reminder.
   * </pre>
   *
   * <code>string time = 1;</code>
   */
  java.lang.String getTime();
  /**
   * <pre>
   * The time of the medication reminder.
   * </pre>
   *
   * <code>string time = 1;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <pre>
   * The name of the medication.
   * </pre>
   *
   * <code>string medication = 2;</code>
   */
  java.lang.String getMedication();
  /**
   * <pre>
   * The name of the medication.
   * </pre>
   *
   * <code>string medication = 2;</code>
   */
  com.google.protobuf.ByteString
      getMedicationBytes();
}
