// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S3-healthActivities.proto

package grpc.service3;

public interface NutritionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:health_activities.NutritionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string meal = 1;</code>
   */
  java.lang.String getMeal();
  /**
   * <code>string meal = 1;</code>
   */
  com.google.protobuf.ByteString
      getMealBytes();

  /**
   * <code>int32 calories_intake = 2;</code>
   */
  int getCaloriesIntake();
}
