// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthActivities.proto

package grpc.example.healthactivities;

/**
 * Protobuf enum {@code health_activities.CaloriesStatus}
 */
public enum CaloriesStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CALORIE_SURPLUS = 0;</code>
   */
  CALORIE_SURPLUS(0),
  /**
   * <code>CALORIE_DEFICIT = 1;</code>
   */
  CALORIE_DEFICIT(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CALORIE_SURPLUS = 0;</code>
   */
  public static final int CALORIE_SURPLUS_VALUE = 0;
  /**
   * <code>CALORIE_DEFICIT = 1;</code>
   */
  public static final int CALORIE_DEFICIT_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CaloriesStatus valueOf(int value) {
    return forNumber(value);
  }

  public static CaloriesStatus forNumber(int value) {
    switch (value) {
      case 0: return CALORIE_SURPLUS;
      case 1: return CALORIE_DEFICIT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CaloriesStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CaloriesStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CaloriesStatus>() {
          public CaloriesStatus findValueByNumber(int number) {
            return CaloriesStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return grpc.example.healthactivities.HealthActivitiesProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final CaloriesStatus[] VALUES = values();

  public static CaloriesStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CaloriesStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:health_activities.CaloriesStatus)
}

