// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthActivities.proto

package grpc.example.healthactivities;

public interface EmergencyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:health_activities.EmergencyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool call_ambulance = 1;</code>
   */
  boolean getCallAmbulance();
}
