// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthActivities.proto

package grpc.example.healthactivities;

/**
 * <pre>
 * Request message for the Exercise method.
 * </pre>
 *
 * Protobuf type {@code health_activities.ExerciseRequest}
 */
public  final class ExerciseRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:health_activities.ExerciseRequest)
    ExerciseRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExerciseRequest.newBuilder() to construct.
  private ExerciseRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExerciseRequest() {
    typeOfExercise_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExerciseRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            typeOfExercise_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_ExerciseRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_ExerciseRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.example.healthactivities.ExerciseRequest.class, grpc.example.healthactivities.ExerciseRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code health_activities.ExerciseRequest.TypeOfExercise}
   */
  public enum TypeOfExercise
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RUNNING = 0;</code>
     */
    RUNNING(0),
    /**
     * <code>CYCLING = 1;</code>
     */
    CYCLING(1),
    /**
     * <code>SWIMMING = 2;</code>
     */
    SWIMMING(2),
    /**
     * <code>WEIGHT_LIFTING = 3;</code>
     */
    WEIGHT_LIFTING(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>RUNNING = 0;</code>
     */
    public static final int RUNNING_VALUE = 0;
    /**
     * <code>CYCLING = 1;</code>
     */
    public static final int CYCLING_VALUE = 1;
    /**
     * <code>SWIMMING = 2;</code>
     */
    public static final int SWIMMING_VALUE = 2;
    /**
     * <code>WEIGHT_LIFTING = 3;</code>
     */
    public static final int WEIGHT_LIFTING_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TypeOfExercise valueOf(int value) {
      return forNumber(value);
    }

    public static TypeOfExercise forNumber(int value) {
      switch (value) {
        case 0: return RUNNING;
        case 1: return CYCLING;
        case 2: return SWIMMING;
        case 3: return WEIGHT_LIFTING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TypeOfExercise>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TypeOfExercise> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TypeOfExercise>() {
            public TypeOfExercise findValueByNumber(int number) {
              return TypeOfExercise.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return grpc.example.healthactivities.ExerciseRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final TypeOfExercise[] VALUES = values();

    public static TypeOfExercise valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TypeOfExercise(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:health_activities.ExerciseRequest.TypeOfExercise)
  }

  public static final int TYPE_OF_EXERCISE_FIELD_NUMBER = 1;
  private int typeOfExercise_;
  /**
   * <code>.health_activities.ExerciseRequest.TypeOfExercise type_of_exercise = 1;</code>
   */
  public int getTypeOfExerciseValue() {
    return typeOfExercise_;
  }
  /**
   * <code>.health_activities.ExerciseRequest.TypeOfExercise type_of_exercise = 1;</code>
   */
  public grpc.example.healthactivities.ExerciseRequest.TypeOfExercise getTypeOfExercise() {
    @SuppressWarnings("deprecation")
    grpc.example.healthactivities.ExerciseRequest.TypeOfExercise result = grpc.example.healthactivities.ExerciseRequest.TypeOfExercise.valueOf(typeOfExercise_);
    return result == null ? grpc.example.healthactivities.ExerciseRequest.TypeOfExercise.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (typeOfExercise_ != grpc.example.healthactivities.ExerciseRequest.TypeOfExercise.RUNNING.getNumber()) {
      output.writeEnum(1, typeOfExercise_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (typeOfExercise_ != grpc.example.healthactivities.ExerciseRequest.TypeOfExercise.RUNNING.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, typeOfExercise_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.example.healthactivities.ExerciseRequest)) {
      return super.equals(obj);
    }
    grpc.example.healthactivities.ExerciseRequest other = (grpc.example.healthactivities.ExerciseRequest) obj;

    boolean result = true;
    result = result && typeOfExercise_ == other.typeOfExercise_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_OF_EXERCISE_FIELD_NUMBER;
    hash = (53 * hash) + typeOfExercise_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.example.healthactivities.ExerciseRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.example.healthactivities.ExerciseRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.example.healthactivities.ExerciseRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.example.healthactivities.ExerciseRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.example.healthactivities.ExerciseRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.example.healthactivities.ExerciseRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.example.healthactivities.ExerciseRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.example.healthactivities.ExerciseRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.example.healthactivities.ExerciseRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.example.healthactivities.ExerciseRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.example.healthactivities.ExerciseRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.example.healthactivities.ExerciseRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.example.healthactivities.ExerciseRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request message for the Exercise method.
   * </pre>
   *
   * Protobuf type {@code health_activities.ExerciseRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:health_activities.ExerciseRequest)
      grpc.example.healthactivities.ExerciseRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_ExerciseRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_ExerciseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.example.healthactivities.ExerciseRequest.class, grpc.example.healthactivities.ExerciseRequest.Builder.class);
    }

    // Construct using grpc.example.healthactivities.ExerciseRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      typeOfExercise_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_ExerciseRequest_descriptor;
    }

    @java.lang.Override
    public grpc.example.healthactivities.ExerciseRequest getDefaultInstanceForType() {
      return grpc.example.healthactivities.ExerciseRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.example.healthactivities.ExerciseRequest build() {
      grpc.example.healthactivities.ExerciseRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.example.healthactivities.ExerciseRequest buildPartial() {
      grpc.example.healthactivities.ExerciseRequest result = new grpc.example.healthactivities.ExerciseRequest(this);
      result.typeOfExercise_ = typeOfExercise_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.example.healthactivities.ExerciseRequest) {
        return mergeFrom((grpc.example.healthactivities.ExerciseRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.example.healthactivities.ExerciseRequest other) {
      if (other == grpc.example.healthactivities.ExerciseRequest.getDefaultInstance()) return this;
      if (other.typeOfExercise_ != 0) {
        setTypeOfExerciseValue(other.getTypeOfExerciseValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.example.healthactivities.ExerciseRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.example.healthactivities.ExerciseRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int typeOfExercise_ = 0;
    /**
     * <code>.health_activities.ExerciseRequest.TypeOfExercise type_of_exercise = 1;</code>
     */
    public int getTypeOfExerciseValue() {
      return typeOfExercise_;
    }
    /**
     * <code>.health_activities.ExerciseRequest.TypeOfExercise type_of_exercise = 1;</code>
     */
    public Builder setTypeOfExerciseValue(int value) {
      typeOfExercise_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.health_activities.ExerciseRequest.TypeOfExercise type_of_exercise = 1;</code>
     */
    public grpc.example.healthactivities.ExerciseRequest.TypeOfExercise getTypeOfExercise() {
      @SuppressWarnings("deprecation")
      grpc.example.healthactivities.ExerciseRequest.TypeOfExercise result = grpc.example.healthactivities.ExerciseRequest.TypeOfExercise.valueOf(typeOfExercise_);
      return result == null ? grpc.example.healthactivities.ExerciseRequest.TypeOfExercise.UNRECOGNIZED : result;
    }
    /**
     * <code>.health_activities.ExerciseRequest.TypeOfExercise type_of_exercise = 1;</code>
     */
    public Builder setTypeOfExercise(grpc.example.healthactivities.ExerciseRequest.TypeOfExercise value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      typeOfExercise_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.health_activities.ExerciseRequest.TypeOfExercise type_of_exercise = 1;</code>
     */
    public Builder clearTypeOfExercise() {
      
      typeOfExercise_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:health_activities.ExerciseRequest)
  }

  // @@protoc_insertion_point(class_scope:health_activities.ExerciseRequest)
  private static final grpc.example.healthactivities.ExerciseRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.example.healthactivities.ExerciseRequest();
  }

  public static grpc.example.healthactivities.ExerciseRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExerciseRequest>
      PARSER = new com.google.protobuf.AbstractParser<ExerciseRequest>() {
    @java.lang.Override
    public ExerciseRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExerciseRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExerciseRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExerciseRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.example.healthactivities.ExerciseRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

