// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthActivities.proto

package grpc.example.healthactivities;

/**
 * Protobuf type {@code health_activities.ExerciseResponse}
 */
public  final class ExerciseResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:health_activities.ExerciseResponse)
    ExerciseResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExerciseResponse.newBuilder() to construct.
  private ExerciseResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExerciseResponse() {
    durationMinutes_ = 0;
    caloriesBurned_ = 0F;
    avgHeartRate_ = 0;
    maxHeartRate_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExerciseResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            durationMinutes_ = input.readInt32();
            break;
          }
          case 21: {

            caloriesBurned_ = input.readFloat();
            break;
          }
          case 24: {

            avgHeartRate_ = input.readInt32();
            break;
          }
          case 32: {

            maxHeartRate_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_ExerciseResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_ExerciseResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.example.healthactivities.ExerciseResponse.class, grpc.example.healthactivities.ExerciseResponse.Builder.class);
  }

  public static final int DURATION_MINUTES_FIELD_NUMBER = 1;
  private int durationMinutes_;
  /**
   * <pre>
   * The duration of the exercise in minutes
   * </pre>
   *
   * <code>int32 duration_minutes = 1;</code>
   */
  public int getDurationMinutes() {
    return durationMinutes_;
  }

  public static final int CALORIES_BURNED_FIELD_NUMBER = 2;
  private float caloriesBurned_;
  /**
   * <pre>
   * The total number of calories burned during the exercise
   * </pre>
   *
   * <code>float calories_burned = 2;</code>
   */
  public float getCaloriesBurned() {
    return caloriesBurned_;
  }

  public static final int AVG_HEART_RATE_FIELD_NUMBER = 3;
  private int avgHeartRate_;
  /**
   * <pre>
   * The average heart rate during the exercise
   * </pre>
   *
   * <code>int32 avg_heart_rate = 3;</code>
   */
  public int getAvgHeartRate() {
    return avgHeartRate_;
  }

  public static final int MAX_HEART_RATE_FIELD_NUMBER = 4;
  private int maxHeartRate_;
  /**
   * <pre>
   * The maximum heart rate achieved during the exercise
   * </pre>
   *
   * <code>int32 max_heart_rate = 4;</code>
   */
  public int getMaxHeartRate() {
    return maxHeartRate_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (durationMinutes_ != 0) {
      output.writeInt32(1, durationMinutes_);
    }
    if (caloriesBurned_ != 0F) {
      output.writeFloat(2, caloriesBurned_);
    }
    if (avgHeartRate_ != 0) {
      output.writeInt32(3, avgHeartRate_);
    }
    if (maxHeartRate_ != 0) {
      output.writeInt32(4, maxHeartRate_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (durationMinutes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, durationMinutes_);
    }
    if (caloriesBurned_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, caloriesBurned_);
    }
    if (avgHeartRate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, avgHeartRate_);
    }
    if (maxHeartRate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, maxHeartRate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.example.healthactivities.ExerciseResponse)) {
      return super.equals(obj);
    }
    grpc.example.healthactivities.ExerciseResponse other = (grpc.example.healthactivities.ExerciseResponse) obj;

    boolean result = true;
    result = result && (getDurationMinutes()
        == other.getDurationMinutes());
    result = result && (
        java.lang.Float.floatToIntBits(getCaloriesBurned())
        == java.lang.Float.floatToIntBits(
            other.getCaloriesBurned()));
    result = result && (getAvgHeartRate()
        == other.getAvgHeartRate());
    result = result && (getMaxHeartRate()
        == other.getMaxHeartRate());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DURATION_MINUTES_FIELD_NUMBER;
    hash = (53 * hash) + getDurationMinutes();
    hash = (37 * hash) + CALORIES_BURNED_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCaloriesBurned());
    hash = (37 * hash) + AVG_HEART_RATE_FIELD_NUMBER;
    hash = (53 * hash) + getAvgHeartRate();
    hash = (37 * hash) + MAX_HEART_RATE_FIELD_NUMBER;
    hash = (53 * hash) + getMaxHeartRate();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.example.healthactivities.ExerciseResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.example.healthactivities.ExerciseResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.example.healthactivities.ExerciseResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.example.healthactivities.ExerciseResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.example.healthactivities.ExerciseResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.example.healthactivities.ExerciseResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.example.healthactivities.ExerciseResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.example.healthactivities.ExerciseResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.example.healthactivities.ExerciseResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.example.healthactivities.ExerciseResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.example.healthactivities.ExerciseResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.example.healthactivities.ExerciseResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.example.healthactivities.ExerciseResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code health_activities.ExerciseResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:health_activities.ExerciseResponse)
      grpc.example.healthactivities.ExerciseResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_ExerciseResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_ExerciseResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.example.healthactivities.ExerciseResponse.class, grpc.example.healthactivities.ExerciseResponse.Builder.class);
    }

    // Construct using grpc.example.healthactivities.ExerciseResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      durationMinutes_ = 0;

      caloriesBurned_ = 0F;

      avgHeartRate_ = 0;

      maxHeartRate_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_ExerciseResponse_descriptor;
    }

    @java.lang.Override
    public grpc.example.healthactivities.ExerciseResponse getDefaultInstanceForType() {
      return grpc.example.healthactivities.ExerciseResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.example.healthactivities.ExerciseResponse build() {
      grpc.example.healthactivities.ExerciseResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.example.healthactivities.ExerciseResponse buildPartial() {
      grpc.example.healthactivities.ExerciseResponse result = new grpc.example.healthactivities.ExerciseResponse(this);
      result.durationMinutes_ = durationMinutes_;
      result.caloriesBurned_ = caloriesBurned_;
      result.avgHeartRate_ = avgHeartRate_;
      result.maxHeartRate_ = maxHeartRate_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.example.healthactivities.ExerciseResponse) {
        return mergeFrom((grpc.example.healthactivities.ExerciseResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.example.healthactivities.ExerciseResponse other) {
      if (other == grpc.example.healthactivities.ExerciseResponse.getDefaultInstance()) return this;
      if (other.getDurationMinutes() != 0) {
        setDurationMinutes(other.getDurationMinutes());
      }
      if (other.getCaloriesBurned() != 0F) {
        setCaloriesBurned(other.getCaloriesBurned());
      }
      if (other.getAvgHeartRate() != 0) {
        setAvgHeartRate(other.getAvgHeartRate());
      }
      if (other.getMaxHeartRate() != 0) {
        setMaxHeartRate(other.getMaxHeartRate());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.example.healthactivities.ExerciseResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.example.healthactivities.ExerciseResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int durationMinutes_ ;
    /**
     * <pre>
     * The duration of the exercise in minutes
     * </pre>
     *
     * <code>int32 duration_minutes = 1;</code>
     */
    public int getDurationMinutes() {
      return durationMinutes_;
    }
    /**
     * <pre>
     * The duration of the exercise in minutes
     * </pre>
     *
     * <code>int32 duration_minutes = 1;</code>
     */
    public Builder setDurationMinutes(int value) {
      
      durationMinutes_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The duration of the exercise in minutes
     * </pre>
     *
     * <code>int32 duration_minutes = 1;</code>
     */
    public Builder clearDurationMinutes() {
      
      durationMinutes_ = 0;
      onChanged();
      return this;
    }

    private float caloriesBurned_ ;
    /**
     * <pre>
     * The total number of calories burned during the exercise
     * </pre>
     *
     * <code>float calories_burned = 2;</code>
     */
    public float getCaloriesBurned() {
      return caloriesBurned_;
    }
    /**
     * <pre>
     * The total number of calories burned during the exercise
     * </pre>
     *
     * <code>float calories_burned = 2;</code>
     */
    public Builder setCaloriesBurned(float value) {
      
      caloriesBurned_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The total number of calories burned during the exercise
     * </pre>
     *
     * <code>float calories_burned = 2;</code>
     */
    public Builder clearCaloriesBurned() {
      
      caloriesBurned_ = 0F;
      onChanged();
      return this;
    }

    private int avgHeartRate_ ;
    /**
     * <pre>
     * The average heart rate during the exercise
     * </pre>
     *
     * <code>int32 avg_heart_rate = 3;</code>
     */
    public int getAvgHeartRate() {
      return avgHeartRate_;
    }
    /**
     * <pre>
     * The average heart rate during the exercise
     * </pre>
     *
     * <code>int32 avg_heart_rate = 3;</code>
     */
    public Builder setAvgHeartRate(int value) {
      
      avgHeartRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The average heart rate during the exercise
     * </pre>
     *
     * <code>int32 avg_heart_rate = 3;</code>
     */
    public Builder clearAvgHeartRate() {
      
      avgHeartRate_ = 0;
      onChanged();
      return this;
    }

    private int maxHeartRate_ ;
    /**
     * <pre>
     * The maximum heart rate achieved during the exercise
     * </pre>
     *
     * <code>int32 max_heart_rate = 4;</code>
     */
    public int getMaxHeartRate() {
      return maxHeartRate_;
    }
    /**
     * <pre>
     * The maximum heart rate achieved during the exercise
     * </pre>
     *
     * <code>int32 max_heart_rate = 4;</code>
     */
    public Builder setMaxHeartRate(int value) {
      
      maxHeartRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The maximum heart rate achieved during the exercise
     * </pre>
     *
     * <code>int32 max_heart_rate = 4;</code>
     */
    public Builder clearMaxHeartRate() {
      
      maxHeartRate_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:health_activities.ExerciseResponse)
  }

  // @@protoc_insertion_point(class_scope:health_activities.ExerciseResponse)
  private static final grpc.example.healthactivities.ExerciseResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.example.healthactivities.ExerciseResponse();
  }

  public static grpc.example.healthactivities.ExerciseResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExerciseResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExerciseResponse>() {
    @java.lang.Override
    public ExerciseResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExerciseResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExerciseResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExerciseResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.example.healthactivities.ExerciseResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

