// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthActivities.proto

package grpc.example.healthactivities;

/**
 * <pre>
 * Predefined heart rate zones.
 * </pre>
 *
 * Protobuf type {@code health_activities.HeartRateZone}
 */
public  final class HeartRateZone extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:health_activities.HeartRateZone)
    HeartRateZoneOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HeartRateZone.newBuilder() to construct.
  private HeartRateZone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HeartRateZone() {
    minBpm_ = 0;
    maxBpm_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HeartRateZone(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            minBpm_ = input.readInt32();
            break;
          }
          case 16: {

            maxBpm_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_HeartRateZone_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_HeartRateZone_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.example.healthactivities.HeartRateZone.class, grpc.example.healthactivities.HeartRateZone.Builder.class);
  }

  public static final int MIN_BPM_FIELD_NUMBER = 1;
  private int minBpm_;
  /**
   * <code>int32 min_bpm = 1;</code>
   */
  public int getMinBpm() {
    return minBpm_;
  }

  public static final int MAX_BPM_FIELD_NUMBER = 2;
  private int maxBpm_;
  /**
   * <code>int32 max_bpm = 2;</code>
   */
  public int getMaxBpm() {
    return maxBpm_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (minBpm_ != 0) {
      output.writeInt32(1, minBpm_);
    }
    if (maxBpm_ != 0) {
      output.writeInt32(2, maxBpm_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (minBpm_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, minBpm_);
    }
    if (maxBpm_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, maxBpm_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.example.healthactivities.HeartRateZone)) {
      return super.equals(obj);
    }
    grpc.example.healthactivities.HeartRateZone other = (grpc.example.healthactivities.HeartRateZone) obj;

    boolean result = true;
    result = result && (getMinBpm()
        == other.getMinBpm());
    result = result && (getMaxBpm()
        == other.getMaxBpm());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MIN_BPM_FIELD_NUMBER;
    hash = (53 * hash) + getMinBpm();
    hash = (37 * hash) + MAX_BPM_FIELD_NUMBER;
    hash = (53 * hash) + getMaxBpm();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.example.healthactivities.HeartRateZone parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.example.healthactivities.HeartRateZone parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.example.healthactivities.HeartRateZone parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.example.healthactivities.HeartRateZone parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.example.healthactivities.HeartRateZone parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.example.healthactivities.HeartRateZone parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.example.healthactivities.HeartRateZone parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.example.healthactivities.HeartRateZone parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.example.healthactivities.HeartRateZone parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.example.healthactivities.HeartRateZone parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.example.healthactivities.HeartRateZone parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.example.healthactivities.HeartRateZone parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.example.healthactivities.HeartRateZone prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Predefined heart rate zones.
   * </pre>
   *
   * Protobuf type {@code health_activities.HeartRateZone}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:health_activities.HeartRateZone)
      grpc.example.healthactivities.HeartRateZoneOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_HeartRateZone_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_HeartRateZone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.example.healthactivities.HeartRateZone.class, grpc.example.healthactivities.HeartRateZone.Builder.class);
    }

    // Construct using grpc.example.healthactivities.HeartRateZone.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      minBpm_ = 0;

      maxBpm_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_HeartRateZone_descriptor;
    }

    @java.lang.Override
    public grpc.example.healthactivities.HeartRateZone getDefaultInstanceForType() {
      return grpc.example.healthactivities.HeartRateZone.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.example.healthactivities.HeartRateZone build() {
      grpc.example.healthactivities.HeartRateZone result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.example.healthactivities.HeartRateZone buildPartial() {
      grpc.example.healthactivities.HeartRateZone result = new grpc.example.healthactivities.HeartRateZone(this);
      result.minBpm_ = minBpm_;
      result.maxBpm_ = maxBpm_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.example.healthactivities.HeartRateZone) {
        return mergeFrom((grpc.example.healthactivities.HeartRateZone)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.example.healthactivities.HeartRateZone other) {
      if (other == grpc.example.healthactivities.HeartRateZone.getDefaultInstance()) return this;
      if (other.getMinBpm() != 0) {
        setMinBpm(other.getMinBpm());
      }
      if (other.getMaxBpm() != 0) {
        setMaxBpm(other.getMaxBpm());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.example.healthactivities.HeartRateZone parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.example.healthactivities.HeartRateZone) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int minBpm_ ;
    /**
     * <code>int32 min_bpm = 1;</code>
     */
    public int getMinBpm() {
      return minBpm_;
    }
    /**
     * <code>int32 min_bpm = 1;</code>
     */
    public Builder setMinBpm(int value) {
      
      minBpm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 min_bpm = 1;</code>
     */
    public Builder clearMinBpm() {
      
      minBpm_ = 0;
      onChanged();
      return this;
    }

    private int maxBpm_ ;
    /**
     * <code>int32 max_bpm = 2;</code>
     */
    public int getMaxBpm() {
      return maxBpm_;
    }
    /**
     * <code>int32 max_bpm = 2;</code>
     */
    public Builder setMaxBpm(int value) {
      
      maxBpm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 max_bpm = 2;</code>
     */
    public Builder clearMaxBpm() {
      
      maxBpm_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:health_activities.HeartRateZone)
  }

  // @@protoc_insertion_point(class_scope:health_activities.HeartRateZone)
  private static final grpc.example.healthactivities.HeartRateZone DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.example.healthactivities.HeartRateZone();
  }

  public static grpc.example.healthactivities.HeartRateZone getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeartRateZone>
      PARSER = new com.google.protobuf.AbstractParser<HeartRateZone>() {
    @java.lang.Override
    public HeartRateZone parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HeartRateZone(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HeartRateZone> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HeartRateZone> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.example.healthactivities.HeartRateZone getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

