// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthActivities.proto

package grpc.example.healthactivities;

/**
 * <pre>
 * Predefined heart rate zones.
 * </pre>
 *
 * Protobuf type {@code health_activities.HeartRateZones}
 */
public  final class HeartRateZones extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:health_activities.HeartRateZones)
    HeartRateZonesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HeartRateZones.newBuilder() to construct.
  private HeartRateZones(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HeartRateZones() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HeartRateZones(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            grpc.example.healthactivities.HeartRateZone.Builder subBuilder = null;
            if (lowIntensity_ != null) {
              subBuilder = lowIntensity_.toBuilder();
            }
            lowIntensity_ = input.readMessage(grpc.example.healthactivities.HeartRateZone.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lowIntensity_);
              lowIntensity_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            grpc.example.healthactivities.HeartRateZone.Builder subBuilder = null;
            if (weightControl_ != null) {
              subBuilder = weightControl_.toBuilder();
            }
            weightControl_ = input.readMessage(grpc.example.healthactivities.HeartRateZone.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(weightControl_);
              weightControl_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            grpc.example.healthactivities.HeartRateZone.Builder subBuilder = null;
            if (aerobic_ != null) {
              subBuilder = aerobic_.toBuilder();
            }
            aerobic_ = input.readMessage(grpc.example.healthactivities.HeartRateZone.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(aerobic_);
              aerobic_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            grpc.example.healthactivities.HeartRateZone.Builder subBuilder = null;
            if (anaerobic_ != null) {
              subBuilder = anaerobic_.toBuilder();
            }
            anaerobic_ = input.readMessage(grpc.example.healthactivities.HeartRateZone.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(anaerobic_);
              anaerobic_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            grpc.example.healthactivities.HeartRateZone.Builder subBuilder = null;
            if (maximum_ != null) {
              subBuilder = maximum_.toBuilder();
            }
            maximum_ = input.readMessage(grpc.example.healthactivities.HeartRateZone.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(maximum_);
              maximum_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_HeartRateZones_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_HeartRateZones_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.example.healthactivities.HeartRateZones.class, grpc.example.healthactivities.HeartRateZones.Builder.class);
  }

  public static final int LOW_INTENSITY_FIELD_NUMBER = 1;
  private grpc.example.healthactivities.HeartRateZone lowIntensity_;
  /**
   * <code>.health_activities.HeartRateZone low_intensity = 1;</code>
   */
  public boolean hasLowIntensity() {
    return lowIntensity_ != null;
  }
  /**
   * <code>.health_activities.HeartRateZone low_intensity = 1;</code>
   */
  public grpc.example.healthactivities.HeartRateZone getLowIntensity() {
    return lowIntensity_ == null ? grpc.example.healthactivities.HeartRateZone.getDefaultInstance() : lowIntensity_;
  }
  /**
   * <code>.health_activities.HeartRateZone low_intensity = 1;</code>
   */
  public grpc.example.healthactivities.HeartRateZoneOrBuilder getLowIntensityOrBuilder() {
    return getLowIntensity();
  }

  public static final int WEIGHT_CONTROL_FIELD_NUMBER = 2;
  private grpc.example.healthactivities.HeartRateZone weightControl_;
  /**
   * <code>.health_activities.HeartRateZone weight_control = 2;</code>
   */
  public boolean hasWeightControl() {
    return weightControl_ != null;
  }
  /**
   * <code>.health_activities.HeartRateZone weight_control = 2;</code>
   */
  public grpc.example.healthactivities.HeartRateZone getWeightControl() {
    return weightControl_ == null ? grpc.example.healthactivities.HeartRateZone.getDefaultInstance() : weightControl_;
  }
  /**
   * <code>.health_activities.HeartRateZone weight_control = 2;</code>
   */
  public grpc.example.healthactivities.HeartRateZoneOrBuilder getWeightControlOrBuilder() {
    return getWeightControl();
  }

  public static final int AEROBIC_FIELD_NUMBER = 3;
  private grpc.example.healthactivities.HeartRateZone aerobic_;
  /**
   * <code>.health_activities.HeartRateZone aerobic = 3;</code>
   */
  public boolean hasAerobic() {
    return aerobic_ != null;
  }
  /**
   * <code>.health_activities.HeartRateZone aerobic = 3;</code>
   */
  public grpc.example.healthactivities.HeartRateZone getAerobic() {
    return aerobic_ == null ? grpc.example.healthactivities.HeartRateZone.getDefaultInstance() : aerobic_;
  }
  /**
   * <code>.health_activities.HeartRateZone aerobic = 3;</code>
   */
  public grpc.example.healthactivities.HeartRateZoneOrBuilder getAerobicOrBuilder() {
    return getAerobic();
  }

  public static final int ANAEROBIC_FIELD_NUMBER = 4;
  private grpc.example.healthactivities.HeartRateZone anaerobic_;
  /**
   * <code>.health_activities.HeartRateZone anaerobic = 4;</code>
   */
  public boolean hasAnaerobic() {
    return anaerobic_ != null;
  }
  /**
   * <code>.health_activities.HeartRateZone anaerobic = 4;</code>
   */
  public grpc.example.healthactivities.HeartRateZone getAnaerobic() {
    return anaerobic_ == null ? grpc.example.healthactivities.HeartRateZone.getDefaultInstance() : anaerobic_;
  }
  /**
   * <code>.health_activities.HeartRateZone anaerobic = 4;</code>
   */
  public grpc.example.healthactivities.HeartRateZoneOrBuilder getAnaerobicOrBuilder() {
    return getAnaerobic();
  }

  public static final int MAXIMUM_FIELD_NUMBER = 5;
  private grpc.example.healthactivities.HeartRateZone maximum_;
  /**
   * <code>.health_activities.HeartRateZone maximum = 5;</code>
   */
  public boolean hasMaximum() {
    return maximum_ != null;
  }
  /**
   * <code>.health_activities.HeartRateZone maximum = 5;</code>
   */
  public grpc.example.healthactivities.HeartRateZone getMaximum() {
    return maximum_ == null ? grpc.example.healthactivities.HeartRateZone.getDefaultInstance() : maximum_;
  }
  /**
   * <code>.health_activities.HeartRateZone maximum = 5;</code>
   */
  public grpc.example.healthactivities.HeartRateZoneOrBuilder getMaximumOrBuilder() {
    return getMaximum();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lowIntensity_ != null) {
      output.writeMessage(1, getLowIntensity());
    }
    if (weightControl_ != null) {
      output.writeMessage(2, getWeightControl());
    }
    if (aerobic_ != null) {
      output.writeMessage(3, getAerobic());
    }
    if (anaerobic_ != null) {
      output.writeMessage(4, getAnaerobic());
    }
    if (maximum_ != null) {
      output.writeMessage(5, getMaximum());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lowIntensity_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLowIntensity());
    }
    if (weightControl_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getWeightControl());
    }
    if (aerobic_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAerobic());
    }
    if (anaerobic_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getAnaerobic());
    }
    if (maximum_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getMaximum());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.example.healthactivities.HeartRateZones)) {
      return super.equals(obj);
    }
    grpc.example.healthactivities.HeartRateZones other = (grpc.example.healthactivities.HeartRateZones) obj;

    boolean result = true;
    result = result && (hasLowIntensity() == other.hasLowIntensity());
    if (hasLowIntensity()) {
      result = result && getLowIntensity()
          .equals(other.getLowIntensity());
    }
    result = result && (hasWeightControl() == other.hasWeightControl());
    if (hasWeightControl()) {
      result = result && getWeightControl()
          .equals(other.getWeightControl());
    }
    result = result && (hasAerobic() == other.hasAerobic());
    if (hasAerobic()) {
      result = result && getAerobic()
          .equals(other.getAerobic());
    }
    result = result && (hasAnaerobic() == other.hasAnaerobic());
    if (hasAnaerobic()) {
      result = result && getAnaerobic()
          .equals(other.getAnaerobic());
    }
    result = result && (hasMaximum() == other.hasMaximum());
    if (hasMaximum()) {
      result = result && getMaximum()
          .equals(other.getMaximum());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLowIntensity()) {
      hash = (37 * hash) + LOW_INTENSITY_FIELD_NUMBER;
      hash = (53 * hash) + getLowIntensity().hashCode();
    }
    if (hasWeightControl()) {
      hash = (37 * hash) + WEIGHT_CONTROL_FIELD_NUMBER;
      hash = (53 * hash) + getWeightControl().hashCode();
    }
    if (hasAerobic()) {
      hash = (37 * hash) + AEROBIC_FIELD_NUMBER;
      hash = (53 * hash) + getAerobic().hashCode();
    }
    if (hasAnaerobic()) {
      hash = (37 * hash) + ANAEROBIC_FIELD_NUMBER;
      hash = (53 * hash) + getAnaerobic().hashCode();
    }
    if (hasMaximum()) {
      hash = (37 * hash) + MAXIMUM_FIELD_NUMBER;
      hash = (53 * hash) + getMaximum().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.example.healthactivities.HeartRateZones parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.example.healthactivities.HeartRateZones parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.example.healthactivities.HeartRateZones parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.example.healthactivities.HeartRateZones parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.example.healthactivities.HeartRateZones parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.example.healthactivities.HeartRateZones parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.example.healthactivities.HeartRateZones parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.example.healthactivities.HeartRateZones parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.example.healthactivities.HeartRateZones parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.example.healthactivities.HeartRateZones parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.example.healthactivities.HeartRateZones parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.example.healthactivities.HeartRateZones parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.example.healthactivities.HeartRateZones prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Predefined heart rate zones.
   * </pre>
   *
   * Protobuf type {@code health_activities.HeartRateZones}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:health_activities.HeartRateZones)
      grpc.example.healthactivities.HeartRateZonesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_HeartRateZones_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_HeartRateZones_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.example.healthactivities.HeartRateZones.class, grpc.example.healthactivities.HeartRateZones.Builder.class);
    }

    // Construct using grpc.example.healthactivities.HeartRateZones.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (lowIntensityBuilder_ == null) {
        lowIntensity_ = null;
      } else {
        lowIntensity_ = null;
        lowIntensityBuilder_ = null;
      }
      if (weightControlBuilder_ == null) {
        weightControl_ = null;
      } else {
        weightControl_ = null;
        weightControlBuilder_ = null;
      }
      if (aerobicBuilder_ == null) {
        aerobic_ = null;
      } else {
        aerobic_ = null;
        aerobicBuilder_ = null;
      }
      if (anaerobicBuilder_ == null) {
        anaerobic_ = null;
      } else {
        anaerobic_ = null;
        anaerobicBuilder_ = null;
      }
      if (maximumBuilder_ == null) {
        maximum_ = null;
      } else {
        maximum_ = null;
        maximumBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.example.healthactivities.HealthActivitiesProto.internal_static_health_activities_HeartRateZones_descriptor;
    }

    @java.lang.Override
    public grpc.example.healthactivities.HeartRateZones getDefaultInstanceForType() {
      return grpc.example.healthactivities.HeartRateZones.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.example.healthactivities.HeartRateZones build() {
      grpc.example.healthactivities.HeartRateZones result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.example.healthactivities.HeartRateZones buildPartial() {
      grpc.example.healthactivities.HeartRateZones result = new grpc.example.healthactivities.HeartRateZones(this);
      if (lowIntensityBuilder_ == null) {
        result.lowIntensity_ = lowIntensity_;
      } else {
        result.lowIntensity_ = lowIntensityBuilder_.build();
      }
      if (weightControlBuilder_ == null) {
        result.weightControl_ = weightControl_;
      } else {
        result.weightControl_ = weightControlBuilder_.build();
      }
      if (aerobicBuilder_ == null) {
        result.aerobic_ = aerobic_;
      } else {
        result.aerobic_ = aerobicBuilder_.build();
      }
      if (anaerobicBuilder_ == null) {
        result.anaerobic_ = anaerobic_;
      } else {
        result.anaerobic_ = anaerobicBuilder_.build();
      }
      if (maximumBuilder_ == null) {
        result.maximum_ = maximum_;
      } else {
        result.maximum_ = maximumBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.example.healthactivities.HeartRateZones) {
        return mergeFrom((grpc.example.healthactivities.HeartRateZones)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.example.healthactivities.HeartRateZones other) {
      if (other == grpc.example.healthactivities.HeartRateZones.getDefaultInstance()) return this;
      if (other.hasLowIntensity()) {
        mergeLowIntensity(other.getLowIntensity());
      }
      if (other.hasWeightControl()) {
        mergeWeightControl(other.getWeightControl());
      }
      if (other.hasAerobic()) {
        mergeAerobic(other.getAerobic());
      }
      if (other.hasAnaerobic()) {
        mergeAnaerobic(other.getAnaerobic());
      }
      if (other.hasMaximum()) {
        mergeMaximum(other.getMaximum());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.example.healthactivities.HeartRateZones parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.example.healthactivities.HeartRateZones) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private grpc.example.healthactivities.HeartRateZone lowIntensity_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.example.healthactivities.HeartRateZone, grpc.example.healthactivities.HeartRateZone.Builder, grpc.example.healthactivities.HeartRateZoneOrBuilder> lowIntensityBuilder_;
    /**
     * <code>.health_activities.HeartRateZone low_intensity = 1;</code>
     */
    public boolean hasLowIntensity() {
      return lowIntensityBuilder_ != null || lowIntensity_ != null;
    }
    /**
     * <code>.health_activities.HeartRateZone low_intensity = 1;</code>
     */
    public grpc.example.healthactivities.HeartRateZone getLowIntensity() {
      if (lowIntensityBuilder_ == null) {
        return lowIntensity_ == null ? grpc.example.healthactivities.HeartRateZone.getDefaultInstance() : lowIntensity_;
      } else {
        return lowIntensityBuilder_.getMessage();
      }
    }
    /**
     * <code>.health_activities.HeartRateZone low_intensity = 1;</code>
     */
    public Builder setLowIntensity(grpc.example.healthactivities.HeartRateZone value) {
      if (lowIntensityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lowIntensity_ = value;
        onChanged();
      } else {
        lowIntensityBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone low_intensity = 1;</code>
     */
    public Builder setLowIntensity(
        grpc.example.healthactivities.HeartRateZone.Builder builderForValue) {
      if (lowIntensityBuilder_ == null) {
        lowIntensity_ = builderForValue.build();
        onChanged();
      } else {
        lowIntensityBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone low_intensity = 1;</code>
     */
    public Builder mergeLowIntensity(grpc.example.healthactivities.HeartRateZone value) {
      if (lowIntensityBuilder_ == null) {
        if (lowIntensity_ != null) {
          lowIntensity_ =
            grpc.example.healthactivities.HeartRateZone.newBuilder(lowIntensity_).mergeFrom(value).buildPartial();
        } else {
          lowIntensity_ = value;
        }
        onChanged();
      } else {
        lowIntensityBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone low_intensity = 1;</code>
     */
    public Builder clearLowIntensity() {
      if (lowIntensityBuilder_ == null) {
        lowIntensity_ = null;
        onChanged();
      } else {
        lowIntensity_ = null;
        lowIntensityBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone low_intensity = 1;</code>
     */
    public grpc.example.healthactivities.HeartRateZone.Builder getLowIntensityBuilder() {
      
      onChanged();
      return getLowIntensityFieldBuilder().getBuilder();
    }
    /**
     * <code>.health_activities.HeartRateZone low_intensity = 1;</code>
     */
    public grpc.example.healthactivities.HeartRateZoneOrBuilder getLowIntensityOrBuilder() {
      if (lowIntensityBuilder_ != null) {
        return lowIntensityBuilder_.getMessageOrBuilder();
      } else {
        return lowIntensity_ == null ?
            grpc.example.healthactivities.HeartRateZone.getDefaultInstance() : lowIntensity_;
      }
    }
    /**
     * <code>.health_activities.HeartRateZone low_intensity = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.example.healthactivities.HeartRateZone, grpc.example.healthactivities.HeartRateZone.Builder, grpc.example.healthactivities.HeartRateZoneOrBuilder> 
        getLowIntensityFieldBuilder() {
      if (lowIntensityBuilder_ == null) {
        lowIntensityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.example.healthactivities.HeartRateZone, grpc.example.healthactivities.HeartRateZone.Builder, grpc.example.healthactivities.HeartRateZoneOrBuilder>(
                getLowIntensity(),
                getParentForChildren(),
                isClean());
        lowIntensity_ = null;
      }
      return lowIntensityBuilder_;
    }

    private grpc.example.healthactivities.HeartRateZone weightControl_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.example.healthactivities.HeartRateZone, grpc.example.healthactivities.HeartRateZone.Builder, grpc.example.healthactivities.HeartRateZoneOrBuilder> weightControlBuilder_;
    /**
     * <code>.health_activities.HeartRateZone weight_control = 2;</code>
     */
    public boolean hasWeightControl() {
      return weightControlBuilder_ != null || weightControl_ != null;
    }
    /**
     * <code>.health_activities.HeartRateZone weight_control = 2;</code>
     */
    public grpc.example.healthactivities.HeartRateZone getWeightControl() {
      if (weightControlBuilder_ == null) {
        return weightControl_ == null ? grpc.example.healthactivities.HeartRateZone.getDefaultInstance() : weightControl_;
      } else {
        return weightControlBuilder_.getMessage();
      }
    }
    /**
     * <code>.health_activities.HeartRateZone weight_control = 2;</code>
     */
    public Builder setWeightControl(grpc.example.healthactivities.HeartRateZone value) {
      if (weightControlBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        weightControl_ = value;
        onChanged();
      } else {
        weightControlBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone weight_control = 2;</code>
     */
    public Builder setWeightControl(
        grpc.example.healthactivities.HeartRateZone.Builder builderForValue) {
      if (weightControlBuilder_ == null) {
        weightControl_ = builderForValue.build();
        onChanged();
      } else {
        weightControlBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone weight_control = 2;</code>
     */
    public Builder mergeWeightControl(grpc.example.healthactivities.HeartRateZone value) {
      if (weightControlBuilder_ == null) {
        if (weightControl_ != null) {
          weightControl_ =
            grpc.example.healthactivities.HeartRateZone.newBuilder(weightControl_).mergeFrom(value).buildPartial();
        } else {
          weightControl_ = value;
        }
        onChanged();
      } else {
        weightControlBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone weight_control = 2;</code>
     */
    public Builder clearWeightControl() {
      if (weightControlBuilder_ == null) {
        weightControl_ = null;
        onChanged();
      } else {
        weightControl_ = null;
        weightControlBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone weight_control = 2;</code>
     */
    public grpc.example.healthactivities.HeartRateZone.Builder getWeightControlBuilder() {
      
      onChanged();
      return getWeightControlFieldBuilder().getBuilder();
    }
    /**
     * <code>.health_activities.HeartRateZone weight_control = 2;</code>
     */
    public grpc.example.healthactivities.HeartRateZoneOrBuilder getWeightControlOrBuilder() {
      if (weightControlBuilder_ != null) {
        return weightControlBuilder_.getMessageOrBuilder();
      } else {
        return weightControl_ == null ?
            grpc.example.healthactivities.HeartRateZone.getDefaultInstance() : weightControl_;
      }
    }
    /**
     * <code>.health_activities.HeartRateZone weight_control = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.example.healthactivities.HeartRateZone, grpc.example.healthactivities.HeartRateZone.Builder, grpc.example.healthactivities.HeartRateZoneOrBuilder> 
        getWeightControlFieldBuilder() {
      if (weightControlBuilder_ == null) {
        weightControlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.example.healthactivities.HeartRateZone, grpc.example.healthactivities.HeartRateZone.Builder, grpc.example.healthactivities.HeartRateZoneOrBuilder>(
                getWeightControl(),
                getParentForChildren(),
                isClean());
        weightControl_ = null;
      }
      return weightControlBuilder_;
    }

    private grpc.example.healthactivities.HeartRateZone aerobic_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.example.healthactivities.HeartRateZone, grpc.example.healthactivities.HeartRateZone.Builder, grpc.example.healthactivities.HeartRateZoneOrBuilder> aerobicBuilder_;
    /**
     * <code>.health_activities.HeartRateZone aerobic = 3;</code>
     */
    public boolean hasAerobic() {
      return aerobicBuilder_ != null || aerobic_ != null;
    }
    /**
     * <code>.health_activities.HeartRateZone aerobic = 3;</code>
     */
    public grpc.example.healthactivities.HeartRateZone getAerobic() {
      if (aerobicBuilder_ == null) {
        return aerobic_ == null ? grpc.example.healthactivities.HeartRateZone.getDefaultInstance() : aerobic_;
      } else {
        return aerobicBuilder_.getMessage();
      }
    }
    /**
     * <code>.health_activities.HeartRateZone aerobic = 3;</code>
     */
    public Builder setAerobic(grpc.example.healthactivities.HeartRateZone value) {
      if (aerobicBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aerobic_ = value;
        onChanged();
      } else {
        aerobicBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone aerobic = 3;</code>
     */
    public Builder setAerobic(
        grpc.example.healthactivities.HeartRateZone.Builder builderForValue) {
      if (aerobicBuilder_ == null) {
        aerobic_ = builderForValue.build();
        onChanged();
      } else {
        aerobicBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone aerobic = 3;</code>
     */
    public Builder mergeAerobic(grpc.example.healthactivities.HeartRateZone value) {
      if (aerobicBuilder_ == null) {
        if (aerobic_ != null) {
          aerobic_ =
            grpc.example.healthactivities.HeartRateZone.newBuilder(aerobic_).mergeFrom(value).buildPartial();
        } else {
          aerobic_ = value;
        }
        onChanged();
      } else {
        aerobicBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone aerobic = 3;</code>
     */
    public Builder clearAerobic() {
      if (aerobicBuilder_ == null) {
        aerobic_ = null;
        onChanged();
      } else {
        aerobic_ = null;
        aerobicBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone aerobic = 3;</code>
     */
    public grpc.example.healthactivities.HeartRateZone.Builder getAerobicBuilder() {
      
      onChanged();
      return getAerobicFieldBuilder().getBuilder();
    }
    /**
     * <code>.health_activities.HeartRateZone aerobic = 3;</code>
     */
    public grpc.example.healthactivities.HeartRateZoneOrBuilder getAerobicOrBuilder() {
      if (aerobicBuilder_ != null) {
        return aerobicBuilder_.getMessageOrBuilder();
      } else {
        return aerobic_ == null ?
            grpc.example.healthactivities.HeartRateZone.getDefaultInstance() : aerobic_;
      }
    }
    /**
     * <code>.health_activities.HeartRateZone aerobic = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.example.healthactivities.HeartRateZone, grpc.example.healthactivities.HeartRateZone.Builder, grpc.example.healthactivities.HeartRateZoneOrBuilder> 
        getAerobicFieldBuilder() {
      if (aerobicBuilder_ == null) {
        aerobicBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.example.healthactivities.HeartRateZone, grpc.example.healthactivities.HeartRateZone.Builder, grpc.example.healthactivities.HeartRateZoneOrBuilder>(
                getAerobic(),
                getParentForChildren(),
                isClean());
        aerobic_ = null;
      }
      return aerobicBuilder_;
    }

    private grpc.example.healthactivities.HeartRateZone anaerobic_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.example.healthactivities.HeartRateZone, grpc.example.healthactivities.HeartRateZone.Builder, grpc.example.healthactivities.HeartRateZoneOrBuilder> anaerobicBuilder_;
    /**
     * <code>.health_activities.HeartRateZone anaerobic = 4;</code>
     */
    public boolean hasAnaerobic() {
      return anaerobicBuilder_ != null || anaerobic_ != null;
    }
    /**
     * <code>.health_activities.HeartRateZone anaerobic = 4;</code>
     */
    public grpc.example.healthactivities.HeartRateZone getAnaerobic() {
      if (anaerobicBuilder_ == null) {
        return anaerobic_ == null ? grpc.example.healthactivities.HeartRateZone.getDefaultInstance() : anaerobic_;
      } else {
        return anaerobicBuilder_.getMessage();
      }
    }
    /**
     * <code>.health_activities.HeartRateZone anaerobic = 4;</code>
     */
    public Builder setAnaerobic(grpc.example.healthactivities.HeartRateZone value) {
      if (anaerobicBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        anaerobic_ = value;
        onChanged();
      } else {
        anaerobicBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone anaerobic = 4;</code>
     */
    public Builder setAnaerobic(
        grpc.example.healthactivities.HeartRateZone.Builder builderForValue) {
      if (anaerobicBuilder_ == null) {
        anaerobic_ = builderForValue.build();
        onChanged();
      } else {
        anaerobicBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone anaerobic = 4;</code>
     */
    public Builder mergeAnaerobic(grpc.example.healthactivities.HeartRateZone value) {
      if (anaerobicBuilder_ == null) {
        if (anaerobic_ != null) {
          anaerobic_ =
            grpc.example.healthactivities.HeartRateZone.newBuilder(anaerobic_).mergeFrom(value).buildPartial();
        } else {
          anaerobic_ = value;
        }
        onChanged();
      } else {
        anaerobicBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone anaerobic = 4;</code>
     */
    public Builder clearAnaerobic() {
      if (anaerobicBuilder_ == null) {
        anaerobic_ = null;
        onChanged();
      } else {
        anaerobic_ = null;
        anaerobicBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone anaerobic = 4;</code>
     */
    public grpc.example.healthactivities.HeartRateZone.Builder getAnaerobicBuilder() {
      
      onChanged();
      return getAnaerobicFieldBuilder().getBuilder();
    }
    /**
     * <code>.health_activities.HeartRateZone anaerobic = 4;</code>
     */
    public grpc.example.healthactivities.HeartRateZoneOrBuilder getAnaerobicOrBuilder() {
      if (anaerobicBuilder_ != null) {
        return anaerobicBuilder_.getMessageOrBuilder();
      } else {
        return anaerobic_ == null ?
            grpc.example.healthactivities.HeartRateZone.getDefaultInstance() : anaerobic_;
      }
    }
    /**
     * <code>.health_activities.HeartRateZone anaerobic = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.example.healthactivities.HeartRateZone, grpc.example.healthactivities.HeartRateZone.Builder, grpc.example.healthactivities.HeartRateZoneOrBuilder> 
        getAnaerobicFieldBuilder() {
      if (anaerobicBuilder_ == null) {
        anaerobicBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.example.healthactivities.HeartRateZone, grpc.example.healthactivities.HeartRateZone.Builder, grpc.example.healthactivities.HeartRateZoneOrBuilder>(
                getAnaerobic(),
                getParentForChildren(),
                isClean());
        anaerobic_ = null;
      }
      return anaerobicBuilder_;
    }

    private grpc.example.healthactivities.HeartRateZone maximum_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.example.healthactivities.HeartRateZone, grpc.example.healthactivities.HeartRateZone.Builder, grpc.example.healthactivities.HeartRateZoneOrBuilder> maximumBuilder_;
    /**
     * <code>.health_activities.HeartRateZone maximum = 5;</code>
     */
    public boolean hasMaximum() {
      return maximumBuilder_ != null || maximum_ != null;
    }
    /**
     * <code>.health_activities.HeartRateZone maximum = 5;</code>
     */
    public grpc.example.healthactivities.HeartRateZone getMaximum() {
      if (maximumBuilder_ == null) {
        return maximum_ == null ? grpc.example.healthactivities.HeartRateZone.getDefaultInstance() : maximum_;
      } else {
        return maximumBuilder_.getMessage();
      }
    }
    /**
     * <code>.health_activities.HeartRateZone maximum = 5;</code>
     */
    public Builder setMaximum(grpc.example.healthactivities.HeartRateZone value) {
      if (maximumBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        maximum_ = value;
        onChanged();
      } else {
        maximumBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone maximum = 5;</code>
     */
    public Builder setMaximum(
        grpc.example.healthactivities.HeartRateZone.Builder builderForValue) {
      if (maximumBuilder_ == null) {
        maximum_ = builderForValue.build();
        onChanged();
      } else {
        maximumBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone maximum = 5;</code>
     */
    public Builder mergeMaximum(grpc.example.healthactivities.HeartRateZone value) {
      if (maximumBuilder_ == null) {
        if (maximum_ != null) {
          maximum_ =
            grpc.example.healthactivities.HeartRateZone.newBuilder(maximum_).mergeFrom(value).buildPartial();
        } else {
          maximum_ = value;
        }
        onChanged();
      } else {
        maximumBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone maximum = 5;</code>
     */
    public Builder clearMaximum() {
      if (maximumBuilder_ == null) {
        maximum_ = null;
        onChanged();
      } else {
        maximum_ = null;
        maximumBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.health_activities.HeartRateZone maximum = 5;</code>
     */
    public grpc.example.healthactivities.HeartRateZone.Builder getMaximumBuilder() {
      
      onChanged();
      return getMaximumFieldBuilder().getBuilder();
    }
    /**
     * <code>.health_activities.HeartRateZone maximum = 5;</code>
     */
    public grpc.example.healthactivities.HeartRateZoneOrBuilder getMaximumOrBuilder() {
      if (maximumBuilder_ != null) {
        return maximumBuilder_.getMessageOrBuilder();
      } else {
        return maximum_ == null ?
            grpc.example.healthactivities.HeartRateZone.getDefaultInstance() : maximum_;
      }
    }
    /**
     * <code>.health_activities.HeartRateZone maximum = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.example.healthactivities.HeartRateZone, grpc.example.healthactivities.HeartRateZone.Builder, grpc.example.healthactivities.HeartRateZoneOrBuilder> 
        getMaximumFieldBuilder() {
      if (maximumBuilder_ == null) {
        maximumBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.example.healthactivities.HeartRateZone, grpc.example.healthactivities.HeartRateZone.Builder, grpc.example.healthactivities.HeartRateZoneOrBuilder>(
                getMaximum(),
                getParentForChildren(),
                isClean());
        maximum_ = null;
      }
      return maximumBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:health_activities.HeartRateZones)
  }

  // @@protoc_insertion_point(class_scope:health_activities.HeartRateZones)
  private static final grpc.example.healthactivities.HeartRateZones DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.example.healthactivities.HeartRateZones();
  }

  public static grpc.example.healthactivities.HeartRateZones getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeartRateZones>
      PARSER = new com.google.protobuf.AbstractParser<HeartRateZones>() {
    @java.lang.Override
    public HeartRateZones parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HeartRateZones(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HeartRateZones> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HeartRateZones> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.example.healthactivities.HeartRateZones getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

