// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthActivities.proto

package grpc.example.healthactivities;

public interface HeartRateZonesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:health_activities.HeartRateZones)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.health_activities.HeartRateZone low_intensity = 1;</code>
   */
  boolean hasLowIntensity();
  /**
   * <code>.health_activities.HeartRateZone low_intensity = 1;</code>
   */
  grpc.example.healthactivities.HeartRateZone getLowIntensity();
  /**
   * <code>.health_activities.HeartRateZone low_intensity = 1;</code>
   */
  grpc.example.healthactivities.HeartRateZoneOrBuilder getLowIntensityOrBuilder();

  /**
   * <code>.health_activities.HeartRateZone weight_control = 2;</code>
   */
  boolean hasWeightControl();
  /**
   * <code>.health_activities.HeartRateZone weight_control = 2;</code>
   */
  grpc.example.healthactivities.HeartRateZone getWeightControl();
  /**
   * <code>.health_activities.HeartRateZone weight_control = 2;</code>
   */
  grpc.example.healthactivities.HeartRateZoneOrBuilder getWeightControlOrBuilder();

  /**
   * <code>.health_activities.HeartRateZone aerobic = 3;</code>
   */
  boolean hasAerobic();
  /**
   * <code>.health_activities.HeartRateZone aerobic = 3;</code>
   */
  grpc.example.healthactivities.HeartRateZone getAerobic();
  /**
   * <code>.health_activities.HeartRateZone aerobic = 3;</code>
   */
  grpc.example.healthactivities.HeartRateZoneOrBuilder getAerobicOrBuilder();

  /**
   * <code>.health_activities.HeartRateZone anaerobic = 4;</code>
   */
  boolean hasAnaerobic();
  /**
   * <code>.health_activities.HeartRateZone anaerobic = 4;</code>
   */
  grpc.example.healthactivities.HeartRateZone getAnaerobic();
  /**
   * <code>.health_activities.HeartRateZone anaerobic = 4;</code>
   */
  grpc.example.healthactivities.HeartRateZoneOrBuilder getAnaerobicOrBuilder();

  /**
   * <code>.health_activities.HeartRateZone maximum = 5;</code>
   */
  boolean hasMaximum();
  /**
   * <code>.health_activities.HeartRateZone maximum = 5;</code>
   */
  grpc.example.healthactivities.HeartRateZone getMaximum();
  /**
   * <code>.health_activities.HeartRateZone maximum = 5;</code>
   */
  grpc.example.healthactivities.HeartRateZoneOrBuilder getMaximumOrBuilder();
}
