// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthActivities.proto

package grpc.example.healthactivities;

public interface HeartRateZoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:health_activities.HeartRateZone)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 min_bpm = 1;</code>
   */
  int getMinBpm();

  /**
   * <code>int32 max_bpm = 2;</code>
   */
  int getMaxBpm();
}
