// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthActivities.proto

package grpc.example.healthactivities;

public interface MedicationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:health_activities.MedicationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The username of the patient.
   * </pre>
   *
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <pre>
   * The username of the patient.
   * </pre>
   *
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
