// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthActivities.proto

package grpc.example.healthactivities;

public interface NutritionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:health_activities.NutritionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 total_calories_intake = 1;</code>
   */
  int getTotalCaloriesIntake();

  /**
   * <code>bool is_caloric_surplus = 2;</code>
   */
  boolean getIsCaloricSurplus();
}
