// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S1-userLogin.proto

package grpc.service1;

/**
 * Protobuf enum {@code LogoutStatus}
 */
public enum LogoutStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LOGOUT_SUCCESSFULL = 0;</code>
   */
  LOGOUT_SUCCESSFULL(0),
  /**
   * <code>INVALID_USERSTATUS = 1;</code>
   */
  INVALID_USERSTATUS(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>LOGOUT_SUCCESSFULL = 0;</code>
   */
  public static final int LOGOUT_SUCCESSFULL_VALUE = 0;
  /**
   * <code>INVALID_USERSTATUS = 1;</code>
   */
  public static final int INVALID_USERSTATUS_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LogoutStatus valueOf(int value) {
    return forNumber(value);
  }

  public static LogoutStatus forNumber(int value) {
    switch (value) {
      case 0: return LOGOUT_SUCCESSFULL;
      case 1: return INVALID_USERSTATUS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LogoutStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LogoutStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LogoutStatus>() {
          public LogoutStatus findValueByNumber(int number) {
            return LogoutStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return grpc.service1.userLoginProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final LogoutStatus[] VALUES = values();

  public static LogoutStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private LogoutStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:LogoutStatus)
}

