// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S1-userLogin.proto

package grpc.service1;

public interface LogoutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LogoutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.LogoutStatus status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.LogoutStatus status = 1;</code>
   */
  grpc.service1.LogoutStatus getStatus();
}
