// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2-healthMonitoring.proto

package grpc.service2;

public interface UserHearthRateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserHearthRateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 curent_hearth_rate = 1;</code>
   */
  int getCurentHearthRate();

  /**
   * <code>string warning_message = 2;</code>
   */
  java.lang.String getWarningMessage();
  /**
   * <code>string warning_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getWarningMessageBytes();
}
