// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2-healthMonitoring.proto

package grpc.service2;

public interface UserStressRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserStressRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 hearth_rate = 1;</code>
   */
  int getHearthRate();

  /**
   * <code>int32 breathing_rate = 2;</code>
   */
  int getBreathingRate();
}
