// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2-healthMonitoring.proto

package grpc.service2;

/**
 * Protobuf type {@code UserSleepRequest}
 */
public  final class UserSleepRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UserSleepRequest)
    UserSleepRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserSleepRequest.newBuilder() to construct.
  private UserSleepRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserSleepRequest() {
    username_ = "";
    snorintTimeMinutes_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserSleepRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (sleepTime_ != null) {
              subBuilder = sleepTime_.toBuilder();
            }
            sleepTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(sleepTime_);
              sleepTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (wakeupTime_ != null) {
              subBuilder = wakeupTime_.toBuilder();
            }
            wakeupTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(wakeupTime_);
              wakeupTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {

            snorintTimeMinutes_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.service2.healthMonitoringProto.internal_static_UserSleepRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.service2.healthMonitoringProto.internal_static_UserSleepRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.service2.UserSleepRequest.class, grpc.service2.UserSleepRequest.Builder.class);
  }

  public static final int USERNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object username_;
  /**
   * <code>string username = 1;</code>
   */
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SLEEP_TIME_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp sleepTime_;
  /**
   * <code>.google.protobuf.Timestamp sleep_time = 2;</code>
   */
  public boolean hasSleepTime() {
    return sleepTime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp sleep_time = 2;</code>
   */
  public com.google.protobuf.Timestamp getSleepTime() {
    return sleepTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sleepTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp sleep_time = 2;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getSleepTimeOrBuilder() {
    return getSleepTime();
  }

  public static final int WAKEUP_TIME_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp wakeupTime_;
  /**
   * <code>.google.protobuf.Timestamp wakeup_time = 3;</code>
   */
  public boolean hasWakeupTime() {
    return wakeupTime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp wakeup_time = 3;</code>
   */
  public com.google.protobuf.Timestamp getWakeupTime() {
    return wakeupTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : wakeupTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp wakeup_time = 3;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getWakeupTimeOrBuilder() {
    return getWakeupTime();
  }

  public static final int SNORINT_TIME_MINUTES_FIELD_NUMBER = 4;
  private int snorintTimeMinutes_;
  /**
   * <code>int32 snorint_time_minutes = 4;</code>
   */
  public int getSnorintTimeMinutes() {
    return snorintTimeMinutes_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
    }
    if (sleepTime_ != null) {
      output.writeMessage(2, getSleepTime());
    }
    if (wakeupTime_ != null) {
      output.writeMessage(3, getWakeupTime());
    }
    if (snorintTimeMinutes_ != 0) {
      output.writeInt32(4, snorintTimeMinutes_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
    }
    if (sleepTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSleepTime());
    }
    if (wakeupTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getWakeupTime());
    }
    if (snorintTimeMinutes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, snorintTimeMinutes_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.service2.UserSleepRequest)) {
      return super.equals(obj);
    }
    grpc.service2.UserSleepRequest other = (grpc.service2.UserSleepRequest) obj;

    boolean result = true;
    result = result && getUsername()
        .equals(other.getUsername());
    result = result && (hasSleepTime() == other.hasSleepTime());
    if (hasSleepTime()) {
      result = result && getSleepTime()
          .equals(other.getSleepTime());
    }
    result = result && (hasWakeupTime() == other.hasWakeupTime());
    if (hasWakeupTime()) {
      result = result && getWakeupTime()
          .equals(other.getWakeupTime());
    }
    result = result && (getSnorintTimeMinutes()
        == other.getSnorintTimeMinutes());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    if (hasSleepTime()) {
      hash = (37 * hash) + SLEEP_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getSleepTime().hashCode();
    }
    if (hasWakeupTime()) {
      hash = (37 * hash) + WAKEUP_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getWakeupTime().hashCode();
    }
    hash = (37 * hash) + SNORINT_TIME_MINUTES_FIELD_NUMBER;
    hash = (53 * hash) + getSnorintTimeMinutes();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.service2.UserSleepRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.service2.UserSleepRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.service2.UserSleepRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.service2.UserSleepRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.service2.UserSleepRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.service2.UserSleepRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.service2.UserSleepRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.service2.UserSleepRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.service2.UserSleepRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.service2.UserSleepRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.service2.UserSleepRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.service2.UserSleepRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.service2.UserSleepRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UserSleepRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UserSleepRequest)
      grpc.service2.UserSleepRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.service2.healthMonitoringProto.internal_static_UserSleepRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.service2.healthMonitoringProto.internal_static_UserSleepRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.service2.UserSleepRequest.class, grpc.service2.UserSleepRequest.Builder.class);
    }

    // Construct using grpc.service2.UserSleepRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      username_ = "";

      if (sleepTimeBuilder_ == null) {
        sleepTime_ = null;
      } else {
        sleepTime_ = null;
        sleepTimeBuilder_ = null;
      }
      if (wakeupTimeBuilder_ == null) {
        wakeupTime_ = null;
      } else {
        wakeupTime_ = null;
        wakeupTimeBuilder_ = null;
      }
      snorintTimeMinutes_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.service2.healthMonitoringProto.internal_static_UserSleepRequest_descriptor;
    }

    @java.lang.Override
    public grpc.service2.UserSleepRequest getDefaultInstanceForType() {
      return grpc.service2.UserSleepRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.service2.UserSleepRequest build() {
      grpc.service2.UserSleepRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.service2.UserSleepRequest buildPartial() {
      grpc.service2.UserSleepRequest result = new grpc.service2.UserSleepRequest(this);
      result.username_ = username_;
      if (sleepTimeBuilder_ == null) {
        result.sleepTime_ = sleepTime_;
      } else {
        result.sleepTime_ = sleepTimeBuilder_.build();
      }
      if (wakeupTimeBuilder_ == null) {
        result.wakeupTime_ = wakeupTime_;
      } else {
        result.wakeupTime_ = wakeupTimeBuilder_.build();
      }
      result.snorintTimeMinutes_ = snorintTimeMinutes_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.service2.UserSleepRequest) {
        return mergeFrom((grpc.service2.UserSleepRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.service2.UserSleepRequest other) {
      if (other == grpc.service2.UserSleepRequest.getDefaultInstance()) return this;
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (other.hasSleepTime()) {
        mergeSleepTime(other.getSleepTime());
      }
      if (other.hasWakeupTime()) {
        mergeWakeupTime(other.getWakeupTime());
      }
      if (other.getSnorintTimeMinutes() != 0) {
        setSnorintTimeMinutes(other.getSnorintTimeMinutes());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.service2.UserSleepRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.service2.UserSleepRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object username_ = "";
    /**
     * <code>string username = 1;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 1;</code>
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp sleepTime_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> sleepTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp sleep_time = 2;</code>
     */
    public boolean hasSleepTime() {
      return sleepTimeBuilder_ != null || sleepTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp sleep_time = 2;</code>
     */
    public com.google.protobuf.Timestamp getSleepTime() {
      if (sleepTimeBuilder_ == null) {
        return sleepTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sleepTime_;
      } else {
        return sleepTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp sleep_time = 2;</code>
     */
    public Builder setSleepTime(com.google.protobuf.Timestamp value) {
      if (sleepTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sleepTime_ = value;
        onChanged();
      } else {
        sleepTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp sleep_time = 2;</code>
     */
    public Builder setSleepTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (sleepTimeBuilder_ == null) {
        sleepTime_ = builderForValue.build();
        onChanged();
      } else {
        sleepTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp sleep_time = 2;</code>
     */
    public Builder mergeSleepTime(com.google.protobuf.Timestamp value) {
      if (sleepTimeBuilder_ == null) {
        if (sleepTime_ != null) {
          sleepTime_ =
            com.google.protobuf.Timestamp.newBuilder(sleepTime_).mergeFrom(value).buildPartial();
        } else {
          sleepTime_ = value;
        }
        onChanged();
      } else {
        sleepTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp sleep_time = 2;</code>
     */
    public Builder clearSleepTime() {
      if (sleepTimeBuilder_ == null) {
        sleepTime_ = null;
        onChanged();
      } else {
        sleepTime_ = null;
        sleepTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp sleep_time = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getSleepTimeBuilder() {
      
      onChanged();
      return getSleepTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp sleep_time = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getSleepTimeOrBuilder() {
      if (sleepTimeBuilder_ != null) {
        return sleepTimeBuilder_.getMessageOrBuilder();
      } else {
        return sleepTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : sleepTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp sleep_time = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getSleepTimeFieldBuilder() {
      if (sleepTimeBuilder_ == null) {
        sleepTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getSleepTime(),
                getParentForChildren(),
                isClean());
        sleepTime_ = null;
      }
      return sleepTimeBuilder_;
    }

    private com.google.protobuf.Timestamp wakeupTime_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> wakeupTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp wakeup_time = 3;</code>
     */
    public boolean hasWakeupTime() {
      return wakeupTimeBuilder_ != null || wakeupTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp wakeup_time = 3;</code>
     */
    public com.google.protobuf.Timestamp getWakeupTime() {
      if (wakeupTimeBuilder_ == null) {
        return wakeupTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : wakeupTime_;
      } else {
        return wakeupTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp wakeup_time = 3;</code>
     */
    public Builder setWakeupTime(com.google.protobuf.Timestamp value) {
      if (wakeupTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        wakeupTime_ = value;
        onChanged();
      } else {
        wakeupTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp wakeup_time = 3;</code>
     */
    public Builder setWakeupTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (wakeupTimeBuilder_ == null) {
        wakeupTime_ = builderForValue.build();
        onChanged();
      } else {
        wakeupTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp wakeup_time = 3;</code>
     */
    public Builder mergeWakeupTime(com.google.protobuf.Timestamp value) {
      if (wakeupTimeBuilder_ == null) {
        if (wakeupTime_ != null) {
          wakeupTime_ =
            com.google.protobuf.Timestamp.newBuilder(wakeupTime_).mergeFrom(value).buildPartial();
        } else {
          wakeupTime_ = value;
        }
        onChanged();
      } else {
        wakeupTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp wakeup_time = 3;</code>
     */
    public Builder clearWakeupTime() {
      if (wakeupTimeBuilder_ == null) {
        wakeupTime_ = null;
        onChanged();
      } else {
        wakeupTime_ = null;
        wakeupTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp wakeup_time = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getWakeupTimeBuilder() {
      
      onChanged();
      return getWakeupTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp wakeup_time = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getWakeupTimeOrBuilder() {
      if (wakeupTimeBuilder_ != null) {
        return wakeupTimeBuilder_.getMessageOrBuilder();
      } else {
        return wakeupTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : wakeupTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp wakeup_time = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getWakeupTimeFieldBuilder() {
      if (wakeupTimeBuilder_ == null) {
        wakeupTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getWakeupTime(),
                getParentForChildren(),
                isClean());
        wakeupTime_ = null;
      }
      return wakeupTimeBuilder_;
    }

    private int snorintTimeMinutes_ ;
    /**
     * <code>int32 snorint_time_minutes = 4;</code>
     */
    public int getSnorintTimeMinutes() {
      return snorintTimeMinutes_;
    }
    /**
     * <code>int32 snorint_time_minutes = 4;</code>
     */
    public Builder setSnorintTimeMinutes(int value) {
      
      snorintTimeMinutes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 snorint_time_minutes = 4;</code>
     */
    public Builder clearSnorintTimeMinutes() {
      
      snorintTimeMinutes_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UserSleepRequest)
  }

  // @@protoc_insertion_point(class_scope:UserSleepRequest)
  private static final grpc.service2.UserSleepRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.service2.UserSleepRequest();
  }

  public static grpc.service2.UserSleepRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserSleepRequest>
      PARSER = new com.google.protobuf.AbstractParser<UserSleepRequest>() {
    @java.lang.Override
    public UserSleepRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserSleepRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserSleepRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserSleepRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.service2.UserSleepRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

