// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2-healthMonitoring.proto

package grpc.service2;

public interface UserStressResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserStressResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float stres_leve = 1;</code>
   */
  float getStresLeve();

  /**
   * <code>string advice = 2;</code>
   */
  java.lang.String getAdvice();
  /**
   * <code>string advice = 2;</code>
   */
  com.google.protobuf.ByteString
      getAdviceBytes();
}
