// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2-healthMonitoring.proto

package grpc.service2;

public interface UserStepsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserStepsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 current_steps = 1;</code>
   */
  int getCurrentSteps();

  /**
   * <code>bool goal_achieved = 2;</code>
   */
  boolean getGoalAchieved();

  /**
   * <code>int32 average_steps = 3;</code>
   */
  int getAverageSteps();
}
