// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthMonitoring.proto

package grpc.example.healthmonitoring;

public interface UserSleepRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserSleepRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>.google.protobuf.Timestamp sleep_time = 2;</code>
   */
  boolean hasSleepTime();
  /**
   * <code>.google.protobuf.Timestamp sleep_time = 2;</code>
   */
  com.google.protobuf.Timestamp getSleepTime();
  /**
   * <code>.google.protobuf.Timestamp sleep_time = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getSleepTimeOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp wakeup_time = 3;</code>
   */
  boolean hasWakeupTime();
  /**
   * <code>.google.protobuf.Timestamp wakeup_time = 3;</code>
   */
  com.google.protobuf.Timestamp getWakeupTime();
  /**
   * <code>.google.protobuf.Timestamp wakeup_time = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getWakeupTimeOrBuilder();

  /**
   * <code>int32 snorint_time_minutes = 4;</code>
   */
  int getSnorintTimeMinutes();
}
